## Data Cleaning

In [2]:
import pandas as pd
import numpy as np

In [27]:
file_path = r"D:\Analyst\DigitalProduct\Automated_Retail_Intelligence\data\raw\online_retail.csv"
df = pd.read_csv(file_path)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [28]:
df.shape

(1067371, 8)

In [29]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [49]:
df["InvoiceDate"].min(), df["InvoiceDate"].max()

(Timestamp('2009-12-01 07:45:00'), Timestamp('2011-12-09 12:50:00'))

In [50]:
df["InvoiceDay"] = df["InvoiceDate"].dt.date

In [51]:
df["Customer ID"] = df["Customer ID"].astype("Int64").astype("string")

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 797815 entries, 0 to 1067370
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      797815 non-null  object
 1   StockCode    797815 non-null  object
 2   Description  797815 non-null  object
 3   Quantity     797815 non-null  int64
 4   InvoiceDate  797815 non-null  datetime64[ns]
 5   Price        797815 non-null  float64
 6   Customer ID  797815 non-null  string
 7   Country      797815 non-null  object
 8   IsCancelled  797815 non-null  bool
 9   Revenue      797815 non-null  float64
 10  InvoiceDay   797815 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(5), string(1)
memory usage: 67.7+ MB

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df = df.drop_duplicates()

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df = df[df["Description"].notna()]

In [57]:
df = df[df["Customer ID"].notna()]

In [58]:
df["IsCancelled"] = df["Invoice"].str.startswith("C")

In [59]:
df["IsCancelled"].value_counts()

IsCancelled
False    779425
True      18390
Name: count, dtype: int64

In [60]:
df[df["Price"] <= 0].shape

(0, 11)

In [61]:
df = df[df["Price"] > 0]

In [62]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [63]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled,Revenue,InvoiceDay
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False,83.4,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False,100.8,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False,30.0,2009-12-01

In [64]:
df.describe()

,Quantity,InvoiceDate,Price,Revenue
count,797815.000000,797815,797815.000000,797815.000000
mean,12.585594,2011-01-02 13:15:39.345813504,3.703057,20.418256
min,-80995.000000,2009-12-01 07:45:00,0.001000,-168469.600000
25%,2.000000,2010-07-02 09:47:00,1.250000,4.350000
50%,5.000000,2010-12-02 12:33:00,1.950000,11.700000
75%,12.000000,2011-07-31 15:50:00,3.750000,19.500000
max,80995.000000,2011-12-09 12:50:00,38970.000000,168469.600000
std,191.163061,NaN,71.395672,313.532519

In [65]:
df.shape

(797815, 11)

In [66]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled,Revenue,InvoiceDay
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False,83.4,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,81.0,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False,100.8,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False,30.0,2009-12-01

In [67]:
output_file = r"D:\Analyst\DigitalProduct\Automated_Retail_Intelligence\data\processed\cleaned_online_data.csv"
df.to_csv(output_file,index=False)

In [68]:
df["Country"].value_counts().head(10)

Country
United Kingdom    716069
Germany            17331
EIRE               16012
France             13896
Netherlands         5132
Spain               3753
Belgium             3109
Switzerland         3057
Portugal            2414
Australia           1887
Name: count, dtype: int64